[tool.poetry]
name = "al"
version = "0.1.0"
description = "my ai shit"
authors = ["chrisaddy <chris.william.addy@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
typer = "^0.4.0"
ell = { path = "../ell" }
pydantic = "^1.8.2"
qdrant-client = {extras = ["fastembed"], version = "^1.10.1"}
pyfzf-iter = "^0.0.1"

[tool.poetry.scripts]
al = "al.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
